const TYPES = {
  AUTH: "AUTH",
  ANSWER: "ANSWER",
  SCORE_UPDATE: "SCORE_UPDATE",
  LEADERBOARD_UPDATE: "LEADERBOARD_UPDATE",
  AUTH_ERROR: "AUTH_ERROR",
  QUESTION: "QUESTION",
  REGISTER: "REGISTER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  GET_TOTAL_QUESTIONS: "GET_TOTAL_QUESTIONS",
  TOTAL_QUESTIONS: "TOTAL_QUESTIONS",
};

module.exports = TYPES;
